#!/bin/sh
#
# Run mbsync if it isn't already running followed by the
# update-mailboxes script to pick up any new or deleted
# IMAP folders.
#
# David Cantrell <david.l.cantrell@gmail.com>
#

PATH=/usr/bin

# Lock things so only one script runs at a time
[ ! "${FLOCKER}" = "$0" ] && exec env FLOCKER="$0" flock -en "$0" "$0" "$@" || :

# Run mbsync
pkill -KILL mbsync
[ -d ${HOME}/logs ] || mkdir -p ${HOME}/logs
mbsync -a -V >${HOME}/logs/mbsync.log 2>&1 || :

# Update mailboxes
[ -x ${HOME}/.mutt/update-mailboxes ] && ${HOME}/.mutt/update-mailboxes

# Update notmuch cache
[ -x /usr/bin/notmuch ] && /usr/bin/notmuch new >${HOME}/logs/notmuch.log 2>&1
