#!/bin/sh
# Originating from:
#     https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
# Modified to generate emacs ctags files and use a slightly more
# insane temporary file.
#
# by: David Cantrell <david.l.cantrell@gmail.com>

set -e

# do not create tag files for git-annex repos
[ -d .git/annex ] && exit 0

PATH=/usr/bin:/usr/local/bin
TMPTAGS="$(mktemp -t git-hook-XXXXXXXXXX.TAGS)"

trap 'rm -f "${TMPTAGS}"' EXIT

CTAGSBIN=
if [ "${CTAGS}" ] && [ -x "${CTAGS}" ]; then
    CTAGSBIN="${CTAGS}"
else
    CTAGSBIN=ctags
fi

git ls-files | ${CTAGSBIN} -e --tag-relative=yes -f "${TMPTAGS}" -L -
mv "${TMPTAGS}" "TAGS"

# for projects that are not code, also git-annex repos
if [ ! -s "TAGS" ]; then
    rm -f "TAGS"
fi
